apiVersion: v1
kind: Service
metadata:
  name: validate-service
  namespace: validate
  labels:
    app: validate
spec:
  type: ClusterIP
  selector:
    app: validate
  ports:
    - name: http
      port: 80
      targetPort: 5001
