apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-store-deployment
  namespace: file-store
  labels:
    app: file-store
    env: dev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: file-store
  template:
    metadata:
      labels:
        app: file-store
    spec:
      containers:
      - name: file-store
        image: registryharbor.bhashini.co.in/bhashini/udyat-dev/file-store:3
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "3"
            memory: "3Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        env:
        - name: ULCA_AZURE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: blob-storage-creds
              key: ULCA_AZURE_CONNECTION_STRING
        - name: ULCA_AZURE_FILE_CONTAINER
          valueFrom:
            secretKeyRef:
              name: common-secret
              key:  ULCA_AZURE_FILE_CONTAINER
        - name: ULCA_AZURE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: common-secret
              key:  ULCA_AZURE_ACCOUNT_NAME
        - name: ULCA_AWS_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ulca-bucket-iam-creds
              key: ULCA_AWS_S3_ACCESS_KEY
        - name: ULCA_AWS_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ulca-bucket-iam-creds
              key: ULCA_AWS_S3_SECRET_KEY
        - name: ULCA_OBJECT_STORE
          value: "AZURE"
        - name: STATUS_INPROGRESS
          value: "In-Progress"
        - name: STATUS_COMPLETED
          value: "Completed"
        - name: STATUS_FAILED
          value: "Failed"
        - name: STATUS_PENDING
          value: "Pending"
        envFrom:
        - secretRef:
            name: common-secret
        volumeMounts:
        - name: model-dir
          mountPath: /opt

      volumes:
      - name: model-dir
        nfs:
          server: 172.29.128.226
          path: /u01/nfs

