apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-deployment
  namespace: ums
  labels:
    app: ums
    env: prod
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: ums
  template:
    metadata:
      labels:
        app: ums
    spec:
      containers:
      - name: ums
        image: ULCA
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "4"
            memory: "4Gi"
          requests:
            cpu: "2"
            memory: "2Gi"
        env:
        - name: API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: model-api-key
              key: MODEL_APIKEY_SECRETKEY
        envFrom:
        - secretRef:
            name: common-secret
        - secretRef:
            name: smtp-creds

