apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ums

resources:
  - ../../base
        

patchesStrategicMerge:
  - deployment.yaml    

images:
  - name: ulca-ums-service
    newName: registryharbor.bhashini.co.in/bhashini/udyat-dev/ulca-ums-service
    newTag: latest
