apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ums
resources:
  - ../../base

images:
  - name: registryharbor.bhashini.co.in/bhashini/udyat-prod/ums
    newName: registryharbor.bhashini.co.in/bhashini/udyat-prod/ulca-ums-service
    newTag: latest
