apiVersion: v1
kind: Service
metadata:
  name: dataset-download-service
  namespace: dataset-download
  labels:
    app: dataset-download
spec:
  selector:
    app: dataset-download
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
